 // NOTE: THIS FILE WAS AUTO-GENERATED BY tools/generate_arch.zig
 // Run `zig build gen-arch` to regenerate

 pub const ap_trampoline = @import("asm/ap_trampoline.asm");
 pub const assembly = @import("assembly.zig");
 pub const constants = @import("constants.zig");
 pub const cpu = @import("cpu.zig");
 pub const memory = @import("memory.zig");
 pub const registers = @import("registers.zig");
 pub const trampoline = @import("trampoline.zig");
 pub const x2apic = @import("apic/x2apic.zig");
 pub const xapic = @import("apic/xapic.zig");
