 // NOTE: THIS FILE WAS AUTO-GENERATED BY tools/generate_arch.zig
 // Run `zig build gen-arch` to regenerate

 pub const apic = @import("apic.zig");
 pub const assembly = @import("assembly.zig");
 pub const constants = @import("constants.zig");
 pub const cpu = @import("cpu.zig");
 pub const descriptors = @import("descriptors.zig");
 pub const entrypoint = @import("entrypoint.zig");
 pub const interrupts = @import("interrupts.zig");
 pub const memory = @import("memory.zig");
 pub const registers = @import("registers.zig");
 pub const smp = @import("smp.zig");
 pub const trampoline = @import("trampoline.zig");
